name = "japari-worker"
main = ".open-next/worker.js"
compatibility_date = "2025-04-01"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]

[vars]

[[d1_databases]]
binding = "DB"
database_name = "japari-d1"
database_id = "0474a3d7-0fa4-49e0-8663-c40615ef3a2c"

[[kv_namespaces]]
binding = "KV"
id = "ee443ab7bdf24d23a4df288ed0636f42"

[assets]
directory = ".open-next/assets"
binding = "ASSETS"
